version: "2"
services:
    web:
        image: contao-2.11:latest # build yourself - see Dockerfile
        container_name: contao2
        ports:
            - "80:80"
        depends_on:
            - mysql
        links:
            - mysql

        volumes:
            - ./contao_data/tl_files:/var/www/html/tl_files
            - ./contao_data/templates:/var/www/html/templates
            - ./contao_data/system/modules:/var/www/html/system/modules

    mysql:
        image: mysql:5.5
        container_name: contao2-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: contaodb
            MYSQL_USER: contao
            MYSQL_PASSWORD: contao
        volumes:
            - ./mysql_data:/var/lib/mysql
      
        
    phpmyadmin:
        image: nazarpc/phpmyadmin
        container_name: contao-phpmyadmin
        ports: 
            - "8888:80"
        links:
            - mysql
