version: "2"
services:
    web:
        image: contao-2.11:latest # build yourself - see Dockerfile
        container_name: contao2
        ports:
            - "80:80"
        depends_on:
            - mysql
        links:
            - mysql

        volumes:
            - ./contao_data/tl_files:/var/www/html/tl_files
            - ./contao_data/templates:/var/www/html/templates
            - ./contao_data/system/modules:/var/www/html/system/modules

    mysql:
        image: mysql:5.5
        container_name: contao2-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: contaodb
            MYSQL_USER: contao
            MYSQL_PASSWORD: contao
        volumes:
            - ./mysql_data:/var/lib/mysql
      
        
    phpmyadmin:
        image: nazarpc/phpmyadmin
        container_name: contao-phpmyadmin
        ports: 
            - "8888:80"
        links:
            - mysql

# how to use:
# 1. build image contao-2.11 from Dockerfile: docker build -t contao-2.11:latest .
# 2. for a fresh Install, uncomment all lines under volumes: except tl_files, then start docker (docker-compose up -d)
# 3. proceed with usual procedure, using http://localhost/contao/install.php, note that localconfig.php is already populated, install PW=contaoadm
# 4. accepst License, create administrator account, log into Backend, have fun :)

Note that with this procedure, you end up with a contao 2.11 core installation, no plugins, no theme whatsoever.
if you want to have your consequent work to be persistent, you will have to add entries to the volumes: section depending on what you install/configure.
everything that resides in the database, will be persistent as this is kept in your local ./mysql-data folder.
the same holds for all (uploaded or edited) files under ./tl_files.
but, be aware, that with this setup, consequently installed contao extensions via the Backend, will NOT persist, the same is true for templates !
in order to make these persistent, too, be sure to:
copy directorys inside docker that have changed (templates, system/modules) to your local contao_data folder, e.g.
docker cp contao2:/var/www/html/templates ./contao_data
once done, you can stop docker, edit docker-compose.yml, uncommenting the corresponding entry under volumes:
then, upon docker restart, you will have your latest changes in templates in place.
