version: '2'

services:
  web:
    image: contao-xdebug:latest 
    container_name: contao-xdebug
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - contao_html_content:/var/www/html
      # the following 2 are needed for xdebug
      - ./logs/xdebug:/logs/xdebug
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      #   be sure to NOT uncomment the following lines BEFORE having completed the Installation - you will get an Error 500 otherwise !
      #- ./contao_data/files:/var/www/html/files
      #- ./contao_data/templates:/var/www/html/templates
      #- ./contao_data/system/modules:/var/www/html/system/modules

  mysql:
    image: mysql:5.7
    container_name: contao-mysql
    volumes:
      - ./mysql_data/:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contao
      MYSQL_USER: contao
      MYSQL_PASSWORD: contao

  phpmyadmin:
    image: nazarpc/phpmyadmin
    container_name: contao-pma
    ports: 
      - "8888:80"
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  contao_html_content:
