version: '2'

services:
  web:
    image: contao4.13:latest
    container_name: c5
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - html_content:/var/www/html
      # the following 2 are needed for xdebug
      #   be sure to NOT uncomment the following lines BEFORE having completed the Installation - you will get an Error 500 otherwise !
      - ./contao_data/files:/var/www/html/files
      - ./contao_data/templates:/var/www/html/templates

  mysql:
    image: mariadb:10.4
    container_name: contao-mysql-c5
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: contaodb
        MYSQL_USER: contao
        MYSQL_PASSWORD: contao
    volumes:
      - ./mysql_data/:/var/lib/mysql/
      
  phpmyadmin:
    image: nazarpc/phpmyadmin
    container_name: contao-pma
    ports: 
      - "8888:80"
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  html_content:
