version: "2"
services:
  web:
    image: contao3.5:latest # first build this image, see Dockerfile
    container_name: contao3
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql

    volumes:
      - ./contao_data/files:/var/www/html/files
  mysql:
    image: mysql:5.7
    container_name: contao-mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: contaodb
        MYSQL_USER: contao
        MYSQL_PASSWORD: contao
    volumes:
      - ./mysql_data/:/var/lib/mysql/
      
        
  phpmyadmin:
    image: nazarpc/phpmyadmin
    container_name: contao-phpmyadmin
    ports: 
      - "8888:80"
    links:
      - mysql
